### ISSUE TITLE
https cactus

### ISSUE THREAD

**Issue by chakravala** [eschnett/GridFunctions.jl#1]
you made a mistake and used https in your link to cactuscode

make the link without https as they don't have a trusty certificate

**Comment by eschnett** [comment]
I reported the problem to the site owner.

**Comment by chakravala** [comment]
their SSL certificate is for their edu website domain, and codecactus is not their main website domain for which they aren't going to buy a certificate obviously. if you want https you should link their edu website, or link to the cactuscode website without https
